#!/bin/csh -f


@ a = 3
while ( $a < 4 )
cd $a
  sed "s/xxx/$a/ ; s/xxxnew/$a/ ; s/xxcut/2.5/ ; s/xxnstep/step<1000/ ; s/xxcreate/0/ ; s/xxrestart/1/ ; s/xxthermo/1/ ; s/pair_detect/0/" ../../MD_3D_structured.cpp > MD_3D_structured.cpp
  sed "s/xxshift/0/ ; s/pair_detect/0/ " ../../pairforce_structured.h > pairforce_structured.h
  
  cp ../../force_structured.h .
  cp ../../structure_definitions.h .
  cp ../../force_structured.cpp .
  cp ../../vctr3D.h .
  cp ../../vctr4D.h .
  cp ../../defs.h .

g++ -std=c++11 MD_3D_structured.cpp force_structured.cpp -O3 -o MD_3D_structured.out 
 ./MD_3D_structured.out | tee log
  cd ..
  @ a = $a + 1
end

@ a = 3
while ( $a < 4 )
cd $a
  sed "s/xxx/$a/ ; s/xxxnew/$a/ ; s/xxcut/2.5/ ; s/xxnstep/step>0/ ; s/xxcreate/0/ ; s/xxrestart/1/ ; s/xxthermo/0/ ; s/pair_detect/1/" ../../MD_3D_structured.cpp > MD_3D_structured.cpp
  sed "s/xxshift/0/ ; s/pair_detect/1/ " ../../pairforce_structured.h > pairforce_structured.h
  
  cp ../../force_structured.h .
  cp ../../structure_definitions.h .
  cp ../../force_structured.cpp .
  cp ../../vctr3D.h .
  cp ../../vctr4D.h .
  cp ../../defs.h .

g++ -std=c++11 -pg MD_3D_structured.cpp force_structured.cpp -O3 -o MD_3D_structured.out 
 ./MD_3D_structured.out | tee log
  cd ..
  @ a = $a + 1
end
