#!/bin/csh -f

@ a = 4
while ( $a < 5 )
cd $a
  sed "s/xxx/$a/ ; s/xxxnew/$a/ ; s/xxcut/2.5/ ; s/xxnstep/step>0/ ; s/xxcreate/0/ ; s/xxrestart/1/ ; s/xxthermo/0/ ; s/pair_detect/1/ ; s/xx_Spring/0/" ../../MD_3D_structured.cpp > MD_3D_structured.cpp
  sed "s/xxshift/0/ ; s/pair_detect/1/ " ../../pairforce_structured.h > pairforce_structured.h
  sed "s|xxcut|5| " ../../defs.h > defs.h

  cp ../../force_structured.h .
  cp ../../structure_definitions.h .
  cp ../../force_structured.cpp .
  cp ../../vctr3D.h .
  cp ../../vctr4D.h .

g++ -std=c++11 -pg MD_3D_structured.cpp force_structured.cpp -O3 -o MD_3D_structured.out 
 ./MD_3D_structured.out | tee log
  cd ..
  @ a = $a + 1
end
